### ISSUE TITLE
Failed to execute 'createOffer' on 'RTCPeerConnection'

### ISSUE THREAD

**Issue by miroslavpejic85** [versatica/mediasoup-client#231]
### Your environment

- Operating system: Mac OS Ventura 13.0.1 (22A400)

- Browsers version: 
  - Chrome: Version 108.0.5359.94 (Official Build) (x86_64)
  - Safari: Version 16.1 (18614.2.9.1.12)
  - Firefox: Version 107.0.1 (64bit)
  - Opera: Version 93.0.4585.39 (x86_64)
  - Microsoft Edge: Version 107.0.1418.68 (Official build) (x86_64)

- npm version: 8.12.1
- mediasoup version: 3.11.3
- mediasoup-client version: 3.6.64

### Issue description

- Produce video or audio using getUserMedia.
- Close created producers.
- Produce video or audio again
- Then the error occurs and producing failed

```bash
DOMException: Failed to execute 'createOffer' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: A BUNDLE group was added in the answer that did not exist in the offer..
```

The only browser that seems work is Brave: Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) (x86_64)

Note: I started having this issue from mc-version `3.6.59`, maybe by [this commit](https://github.com/versatica/mediasoup-client/commit/81d8885f19d9819776dedd91d3ac68e2ab62c1c0).

Thank you.

**Comment by ibc** [comment]
Fixed in https://github.com/versatica/mediasoup-client/commit/fdd0411df6616ce84195e83f17c906fc070f2601. Please check the commit message since this is just fixed for Firefox in which there was a reason for the issue to happen.

**Comment by ibc** [comment]
Version 3.6.65 released with the fix.

**Comment by miroslavpejic85** [comment]
Hi Ibc,
I tried the version 3.6.65, but on my side, now the producer error still on in:

- Chrome: Version 108.0.5359.94 (Official Build) (x86_64)
- Safari: Version 16.1 (18614.2.9.1.12)
- Opera: Version 93.0.4585.39 (x86_64)
- Microsoft Edge: Version 107.0.1418.68 (Official build) (x86_64)
- Brave: Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) (x86_64)

Works well now only on Firefox: Version 107.0.1 (64bit)

Anyway, without the `transceiver.stop()` as in v 3.6.58, all work good, in all browsers mentioned before.

Thank you for your quick reply and your time.

**Comment by ibc** [comment]
Please specify your OS and where you run it (which app). Does it happen for you in those browsers in the official mediasoup demo? (Please ensure you reload the web app so JS is not cached).

**Comment by miroslavpejic85** [comment]
Hi ibc,

Sorry, the problem seems only in the `audio` producer (`close-produce`)

- Produce audio using getUserMedia().
- Close created producers.
- Produce audio again
- Then the error occurs and producing failed.

I tried all this with only video producer, and works good, in all browsers mentioned before.

On the official mediasoup demo, I see the audio is `paused` then `resumed`, and here I not see errors.

So can you please try to `close` then `produce` the audio, instead of pause - resume, and see if you has the same issue? 

Note: The only browser where both video/audio close-produce works is FireFox, where you removed the `transceiver.stop()`

Thank you so much.

**Comment by ibc** [comment]
Ok, it makes sense because we don't really close the FIRST m section which usually it's the audio one. Funny thing is that I explained it years ago:

https://webrtchacks.com/webrtc-sdp-inaki-baz-castillo/

**Comment by ibc** [comment]
Fixed in 3.6.66

**Comment by miroslavpejic85** [comment]
Yeah, interesting article, thank you very much and I can confirm that now everything works as expected.

**Comment by ibc** [comment]
Thanks a lot.
